fixing github workflow
onja-org/vamalaka-haukea pull request #1
Opened 2021-07-02 11:57 UTC by starjardin

Hi team,

Have a look at the fixing github workflow task.

Refs: fix 41k9rg

Haukea

Thanks

2021-07-03 06:07 UTC, vahona approved these changes

2021-07-03 06:19 UTC, Fodilahy-mena approved these changes

2021-07-06 06:00 UTC, andrzej-onja requested changes

2021-07-06 06:00 UTC, andrzej-onja commented on .github/workflows/actions.yml
> +    - run: yarn run cypress:ci
why did you removed `- run: yarn run build`
please add it back

2021-07-06 06:48 UTC, andrzej-onja requested changes

2021-07-06 06:48 UTC, andrzej-onja commented on .github/workflows/actions.yml
> +    - run: yarn run cypress:ci
please move `- run: yarn run cypress:ci` above `- run: yarn run build`

2021-07-06 07:35 UTC, andrzej-onja approved these changes

2021-07-06 11:02 UTC, merged